### ISSUE TITLE
Error opening private.key TransIP DNS

### ISSUE THREAD

**Issue by BurgerhoutJ** [kchristensen/udm-le#35]
Hi,

I followed the manual, customized the .env-file and while it's running, I can see that the script is downloading some files from lego, created a personal key pair, but then the script needs to check via the API at TransIP. But everytime, the script is saying that he can't find the .key-file.
I see the file with the ls-command and via WinSCP in the same directory as the .env- and .sh-files.
See the screenshots for more info.

Who can help me? Thanks in advance.

![image](https://user-images.githubusercontent.com/25769575/119513824-d7d74f00-bd74-11eb-867b-44b46ef9074b.png)
![image](https://user-images.githubusercontent.com/25769575/119513864-e45ba780-bd74-11eb-8957-fdc65ef525b5.png)

**Comment by kchristensen** [comment]
I'm not familiar with TransIP, but the issue is that lego is running in a Docker container, not natively on your UDMP. 

If you can, you'll want to specify the location of the transip.key file to `/root/.secrets/transip.key` and then put the transip.key file in `/mnt/data/udm-le/.secrets/`, which is a directory you'll create on your UDMP. This directory gets mounted into the lego container when it runs, so lego will be able to see it.

**Comment by BurgerhoutJ** [comment]
Thanks... One step further. Now I have to check something with API and so on.

`acme: error presenting token: transip: could not get token from authenticator: error requesting token: Your key signature is invalid or API is not enabled in your account`

Will let you know what the outcome is.

**Comment by BurgerhoutJ** [comment]
For now I will stop. Maybe I'm gonna do it in a later stadium. So issue closed.
