### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by deeps-1987** [kchristensen/udm-le#37]
Hi

I am new to this and followed along with your steps on my UDM-P and keep getting the following error when I try to run "/mnt/data/udm-le/udm-le.sh initial":

```
"root@ubnt:/# /mnt/data/udm-le/udm-le.sh initial
bash: /mnt/data/udm-le/udm-le.sh: No such file or directory"
```
I can only navigate to /mnt/ and when I "ls" only "persistent" shows but Winscp clearly shows more
![image](https://user-images.githubusercontent.com/86173500/122658559-b183b400-d166-11eb-93b4-d134480e4a27.png)

![image](https://user-images.githubusercontent.com/86173500/122658573-cceebf00-d166-11eb-9d81-ec104a432a4f.png)

 - UniFi OS: Firmware Version 1.9.3 (Network - 6.2.25)
 - Hardware Type:  UDM-Pro

**Comment by kchristensen** [comment]
I saw you edited this post a couple of times, but I think your issue is that in your first screenshot you've posted you're doing that `ls` after running `unifi-os shell`? If so, you're exec'ing into the unifi-os container on the host by doing so, which is incorrect.

You'll want to run the mkdir and what have you after ssh'ing into the host as root. Nothing about udm-le requires you shell into the container via `unifi-os shell`. I should probably amend the instructions to make that a bit more clear, I think people are used to running `unifi-os shell` for command line upgrades and stuff and think you have to do that every time.

**Comment by deeps-1987** [comment]
> I saw you edited this post a couple of times, but I think your issue is that in your first screenshot you've posted you're doing that `ls` after running `unifi-os shell`? If so, you're exec'ing into the unifi-os container on the host by doing so, which is incorrect.
> 
> You'll want to run the mkdir and what have you after ssh'ing into the host as root. Nothing about udm-le requires you shell into the container via `unifi-os shell`. I should probably amend the instructions to make that a bit more clear, I think people are used to running `unifi-os shell` for command line upgrades and stuff and think you have to do that every time.

Perfect, thanks that fixed that issue.
Now i am getting the issue `"cloudflare: failed to find zone"` even though it exists.
My API settings are : 
![image](https://user-images.githubusercontent.com/86173500/122799850-2582a100-d2ba-11eb-822f-47e77507cf3b.png)

**Comment by deeps-1987** [comment]
ignore, fixed it.
Thank you :D
